### PR TITLE
submission.txt

### PR DESCRIPTION
**Pull request by Tyfn46**

### CODE REVIEW

**Comment by Tyfn46** [comment]
Form Submitted 15 May 2022 01:32 (UTC+3)

**Comment by Tyfn46** [comment]
Form Submitted,  16 May 2022 - 15:05 (UTC+3)

**Comment by pablozsc** [comment]
hello Tyfn46. This is moderator Pablo from Concordium.

We noticed that you filled out the form 2 times and provided us with 2 different wallets.
The main purpose of this message is to try to reveal your valid and correct wallet address.
We got 2 entries:

1. 3cV...xj7
2. 4ip...Kwz

Please tell me which address is correct. This is required for testnet4 rewards to be credited.

**Comment by Tyfn46** [comment]
Hello Pablo.
Thank you for giving information.

My wallet address is (3cV...xj7) 
Other address is not mine. There must have been a mistake.

**Pull request closed without merging**
