### PR TITLE
Submission

### PR DESCRIPTION
**Pull request by amonxx**

### CODE REVIEW

**Comment by amonxx** [comment]
form submitted-13/05/2022 (UTC +3) 16:56

**Comment by pablozsc** [comment]
hello amonxx! This is moderator Pablo from Concordium.

We noticed that you filled out the form 2 times and provided us with 2 different wallets.
The main purpose of this message is to try to reveal your valid and correct wallet address.
I see that your old nickname is erzurumlee. 
We got 2 entries:

1. 42A...QXx
2. 4Ds...xJK

Please tell me which address is correct. This is required for testnet4 rewards to be credited.

**Comment by amonxx** [comment]
In github pull requests, the date that matches the submission time must
match the address  42ACnr16qnqWnnAaGXK4kRYeEKnMBSvqro87fr1MDP6xHinQXx  I
don't know about submitting 2 forms. my address is
42ACnr16qnqWnnAaGXK4kRYeEKnMBSvqro87fr1MDP6xHinQXx

23 May 2022 Pzt, saat 21:02 tarihinde pablozsc ***@***.***>
şunu yazdı:

**Comment by pablozsc** [comment]
Well thank you. I'll write down that your address is 42A...QXx
rewards will be sent to you at this address.

Perhaps the hitch is that we have a record that your old username is erzurumlee. This user also filled out the form and provided the address 4Ds...xJK

**Pull request closed without merging**
