### PR TITLE
OT4-C1 and OT4-C2 Russian_language

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by senichevalexey** [comment]
"Form Submitted" 
15:21
MSK, UTC+3H

**Comment by ghost** [comment]
"Form Submitted" 
15:21
MSK, UTC+3H

**Comment by pablozsc** [comment]
hello ZunamiLab. This is moderator Pablo from Concordium.

We noticed that you filled out the form 2 times and provided us with 2 different wallets.
The main purpose of this message is to try to reveal your valid and correct wallet address.
We got 2 entries:

1. 3zF...VSu
2. 3tT...EJN

Please tell me which address is correct. This is required for testnet4 rewards to be credited.

**Comment by ghost** [comment]
Hi, our wallet is 3tToSS4CAH3e5Nh2CxNMGDkcznRgVeeThvb7xSFcfSEEyewEJN
Thx 😁

**Pull request closed without merging**
